### ISSUE TITLE
not working properly

### ISSUE THREAD

**Issue by ArvindReddy-t** [Kartik-Katkar/OrganEase#5]
we are using your code as a reference for our project but 
![Screenshot 2024-04-02 071807](https://github.com/Kartik-Katkar/OrganEase/assets/154102004/4b331ffa-8e11-4704-97b9-b67d58b5910c)

the screen  is buffering when started. and can you tell me how to connect too mongoDB correctly.

**Comment by Kartik-Katkar** [comment]
Hello, to connect to MongoDB, you need to update the path in the environment file of your MongoDB Atlas cluster if you are using one in server folder.

![image](https://github.com/Kartik-Katkar/OrganEase/assets/97340275/9aad343b-6b1e-494f-b14d-8d877e10c600)
